Algoritmo "7i.QuadradoDaDiferanca"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Lorena Rosa
// Data atual  : 12/04/2025
Var
// Seção de Declarações das variáveis 
   a, b, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   Escreva("Digite um valor inteiro para A: ")
   Leia (a)
   Escreva ("Digite um valor inteiro para B: ")
   Leia (b)
   
   resultado <- a - b
   resultado <- resultado * resultado
   
   Escreva ("O quadrado da diferença de A por B é: ", resultado)

Fimalgoritmo