Algoritmo "MaiorOuMenorQue10"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibe se um número é maior, menor ou igual a 10.
// Autor(a)    : Lorena Rosa
// Data atual  : 22/03/2025
Var
   // Seção de Declarações das variáveis
   valor: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva ("Bem Vindo")
   Escreva ("Digite um valor inteiro: ")
   Leia (valor)
   SE valor > 10 entao
      escreva ("Esse valor é maior que 10!")
   senao
      se valor < 10 entao
         escreva ("Esse valor é menr que 10!")
      senao
         escreva ("Esse valor é igual a 10!")
      FIMSE
   FIMSE
Fimalgoritmo
