Algoritmo "OrdemDecrescente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita um valor e decresce ele até 0.
// Autor(a)    : Lorena Rosa
// Data atual  : 24/03/2025
Var
   // Seção de Declarações das variáveis
   valor, contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   Escreva ("Digite um valor: ")
   Leia (contador)
   enquanto contador > 0 faca
      Escreva (contador)
      contador <- contador - 1
   fimenquanto

Fimalgoritmo