Algoritmo "AreaRetangulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula a área de um retângulo
// Autor(a)    : Lorena Rosa
// Data atual  : 22/03/2025

Var
   base, altura, area: real


Inicio
   Escreva ("Digite qual o valor da altura do retângulo: ")
   Leia (base)
   Escreva ("Digite qual o valor da base do retângulo: ")
   Leia (altura)
   area <- base * altura
   Escreva ("A área do retângulo é igual a: ", area)


Fimalgoritmo