Algoritmo "Divisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Realiza um cálculo de divisão.
// Autor(a)    : Lorena Rosa
// Data atual  : 22/03/2025

Var
   numero1, numero2, divisao: real

Inicio
   Escreva ("Digite o primeiro valor: ")
   Leia (numero1)
   Escreva ("Digite o segundo valor: ")
   Leia (numero2)
   divisao <- numero1 / numero2
   Escreva ("A divisão entre os números ", numero1, " e ", numero2, " é igual a: ", divisao)

Fimalgoritmo