Algoritmo "Multiplicacao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Realiza uma operação de multiplicação.
// Autor(a)    : Lorena Rosa
// Data atual  : 22/03/2025
Var
   numero1, numero2, multi: inteiro


Inicio
      Escreva ("Digite o primeiro valor: ")
      Leia (numero1)
      Escreva ("Digite o segundo valor: ")
      Leia (numero2)
      multi <- numero1 * numero2
      Escreva ("A multiplicação entre os números ", numero1, " e ", numero2, " é igual a ", multi)
Fimalgoritmo