Algoritmo "Soma"
// Disciplina : Lógica de programação com javascript
// Professor : Jailson Costa dos Santos
// Descrição : Realiza um cálculo de adição.
// Autor(a) : Lorena Rosa
// Data atual : 13/03/2025
Var
   numero1, numero2, soma: inteiro
   
Inicio
   Escreva ("Digite o primeiro valor: ")
   Leia (numero1)
   Escreva ("Digite o segundo valor: ")
   Leia (numero2)
   soma <- numero1 + numero2
   Escreva ("A soma entre os valores é igual a: ", soma)
   
Fimalgoritmo