Algoritmo "L03D.ImparesDe0A20"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exibe os números ímpares de 0 a 20
// Autor(a)    : Lorena Rosa
// Data atual  : 13/04/2025
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 0

   Enquanto contador < 21 faca
      Se contador % 2 = 1 entao
         Escreval (contador)
      Fimse
      contador <- contador + 1
   Fimenquanto


Fimalgoritmo